# Site
name: Daily Daily On !!
title: IT 기술을 활용한 업무 자동화와 미국 주식에 대한 콘텐츠를 즐겨보세요.
description: IT 기술을 활용한 업무 자동화와 미국 주식에 대한 콘텐츠를 즐겨보세요.
logo: assets/images/logo.png
image: assets/images/logo.png
lang: ko_KR
favicon: assets/images/logo.png
baseurl: 
google_analytics: UA-46278016-1
disqus: https-picsen-github-io
mailchimp-list: https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  picsen:
    name: picsen
    display_name: 아지기    
    avatar: assets/images/avatar.jpg
    gravatar: 56a7055200eb4ee82b064d3d9ab47788
    email: picsen@naver.com
    web: https://picsen.github.io
    twitter: https://twitter.com/picsen
    description: 풀스택 시니어 개발자

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: /category/:name/
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: disabled
adsense-data-ad-client: ca-pub-3412143450191416
adsense-data-ad-slot: 1363087678

# Lazy Images ("enabled" or "disabled")
lazyimages: disabled

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock, Mediumish_template.xlsx, Templates, .obsidian]

#timezone: Asia/Seoul
future: true
